logging:
  level:
    root: INFO
server:
  port: 9000
  servlet:
    contextPath: /api
spring:
  application:
    name: pourrfot-server
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost/pourrfot"
    username: root
    password: 123456
management:
  endpoints:
    web:
      exposure:
        include: "*"
