###
POST http://localhost:9000/api/courses/1/students
Accept: application/json
Content-Type: application/json

{
    "courseId": 1,
    "groupId": 1,
    "studentId": 1,
    "studentName": "蔡佳昊"
}

###
GET http://localhost:9000/api/courses/1/students
Accept: application/json
Content-Type: application/json

###
GET http://localhost:9000/api/courses/1/students/1
Accept: application/json
Content-Type: application/json


###
PUT http://localhost:9000/api/courses/1/students/1
Accept: application/json
Content-Type: application/json

{
    "courseId": 1,
    "groupId": 1,
    "studentId": 1,
    "studentName": "蔡佳昊",
    "scoreStructure": [
        {
            "description": "total",
            "score": 100,
            "weight": 1
        }
    ]
}

###
DELETE http://localhost:9000/api/courses/1/students/1
