# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. 
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      URL: ${{ secrets.ALIYUN_DOCKER_REGISTRY_HOST }}/${{ secrets.ALIYUN_DOCKER_REGISTRY_NAMESPACE }}/pourrfot-server:latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy to Aliyun LightHouse
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ALIYUN_LIGHTHOUSE_HOST }}
          username: ${{ secrets.ALIYUN_LIGHTHOUSE_USERNAME }}
          key: ${{ secrets.ALIYUN_LIGHTHOUSE_KEY }}
          script: |
            docker stop $(docker ps --filter name=pourrfot-server -q)
            docker rm -f $(docker ps -a --filter name=pourrfot-server -q)
            docker pull ${{URL}}
            docker run -d -p 9000:9000 ${{URL}}
