# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: echo image version
        id: echo-image-version
        run: echo "::set-output name=CUSTOM_IMAGE_VERSION::`git --no-pager log -1 --format="%ad" --date=format:"%Y%m%d"`-`git describe --always`"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Build And Push Docker Image
        id: buildAndPushImage
        uses: risfeng/docker-image-build-push-action@v1.0
        with:
          registry_url: ${{ secrets.ALIYUN_DOCKER_REGISTRY_URL }}
          namespaces: ${{ secrets.ALIYUN_DOCKER_REGISTRY_NAMESPACE }}
          repository_name: 'pourrfot-server'
          user_name: ${{ secrets.ALIYUN_DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_DOCKER_REGISTRY_PASSWORD }}
          image_version: ${{ steps.echo-image-version.outputs.CUSTOM_IMAGE_VERSION }}
          docker_file: '.'
      - name: Get pre step result output image_pull_url
        run: echo "The image pull url was ${{ steps.buildAndPushImage.outputs.image_pull_url }}"
